# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.activities_api import ActivitiesApi


class TestActivitiesApi(unittest.IsolatedAsyncioTestCase):
    """ActivitiesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ActivitiesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_activity(self) -> None:
        """Test case for create_activity

        """
        pass

    async def test_delete_activity(self) -> None:
        """Test case for delete_activity

        """
        pass

    async def test_get_activities(self) -> None:
        """Test case for get_activities

        """
        pass

    async def test_get_activity_statistics(self) -> None:
        """Test case for get_activity_statistics

        """
        pass


if __name__ == '__main__':
    unittest.main()
