# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.models.user_avatar_color import UserAvatarColor

class TestUserAvatarColor(unittest.TestCase):
    """UserAvatarColor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserAvatarColor(self):
        """Test UserAvatarColor"""
        # inst = UserAvatarColor()

if __name__ == '__main__':
    unittest.main()
