# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.faces_api import FacesApi


class TestFacesApi(unittest.IsolatedAsyncioTestCase):
    """FacesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FacesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_face(self) -> None:
        """Test case for create_face

        """
        pass

    async def test_delete_face(self) -> None:
        """Test case for delete_face

        """
        pass

    async def test_get_faces(self) -> None:
        """Test case for get_faces

        """
        pass

    async def test_reassign_faces_by_id(self) -> None:
        """Test case for reassign_faces_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
