# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.models.notification_type import NotificationType

class TestNotificationType(unittest.TestCase):
    """NotificationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationType(self):
        """Test NotificationType"""
        # inst = NotificationType()

if __name__ == '__main__':
    unittest.main()
