# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.models.sync_entity_type import SyncEntityType

class TestSyncEntityType(unittest.TestCase):
    """SyncEntityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSyncEntityType(self):
        """Test SyncEntityType"""
        # inst = SyncEntityType()

if __name__ == '__main__':
    unittest.main()
