# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.IsolatedAsyncioTestCase):
    """AuthenticationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AuthenticationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_change_password(self) -> None:
        """Test case for change_password

        """
        pass

    async def test_change_pin_code(self) -> None:
        """Test case for change_pin_code

        """
        pass

    async def test_get_auth_status(self) -> None:
        """Test case for get_auth_status

        """
        pass

    async def test_lock_auth_session(self) -> None:
        """Test case for lock_auth_session

        """
        pass

    async def test_login(self) -> None:
        """Test case for login

        """
        pass

    async def test_logout(self) -> None:
        """Test case for logout

        """
        pass

    async def test_reset_pin_code(self) -> None:
        """Test case for reset_pin_code

        """
        pass

    async def test_setup_pin_code(self) -> None:
        """Test case for setup_pin_code

        """
        pass

    async def test_sign_up_admin(self) -> None:
        """Test case for sign_up_admin

        """
        pass

    async def test_unlock_auth_session(self) -> None:
        """Test case for unlock_auth_session

        """
        pass

    async def test_validate_access_token(self) -> None:
        """Test case for validate_access_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
