# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.IsolatedAsyncioTestCase):
    """SessionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SessionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_session(self) -> None:
        """Test case for create_session

        """
        pass

    async def test_delete_all_sessions(self) -> None:
        """Test case for delete_all_sessions

        """
        pass

    async def test_delete_session(self) -> None:
        """Test case for delete_session

        """
        pass

    async def test_get_sessions(self) -> None:
        """Test case for get_sessions

        """
        pass

    async def test_lock_session(self) -> None:
        """Test case for lock_session

        """
        pass


if __name__ == '__main__':
    unittest.main()
