# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.IsolatedAsyncioTestCase):
    """APIKeysApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = APIKeysApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_api_key(self) -> None:
        """Test case for create_api_key

        """
        pass

    async def test_delete_api_key(self) -> None:
        """Test case for delete_api_key

        """
        pass

    async def test_get_api_key(self) -> None:
        """Test case for get_api_key

        """
        pass

    async def test_get_api_keys(self) -> None:
        """Test case for get_api_keys

        """
        pass

    async def test_update_api_key(self) -> None:
        """Test case for update_api_key

        """
        pass


if __name__ == '__main__':
    unittest.main()
