# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.libraries_api import LibrariesApi


class TestLibrariesApi(unittest.IsolatedAsyncioTestCase):
    """LibrariesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LibrariesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_library(self) -> None:
        """Test case for create_library

        """
        pass

    async def test_delete_library(self) -> None:
        """Test case for delete_library

        """
        pass

    async def test_get_all_libraries(self) -> None:
        """Test case for get_all_libraries

        """
        pass

    async def test_get_library(self) -> None:
        """Test case for get_library

        """
        pass

    async def test_get_library_statistics(self) -> None:
        """Test case for get_library_statistics

        """
        pass

    async def test_scan_library(self) -> None:
        """Test case for scan_library

        """
        pass

    async def test_update_library(self) -> None:
        """Test case for update_library

        """
        pass

    async def test_validate(self) -> None:
        """Test case for validate

        """
        pass


if __name__ == '__main__':
    unittest.main()
