# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.jobs_api import JobsApi


class TestJobsApi(unittest.IsolatedAsyncioTestCase):
    """JobsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = JobsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_job(self) -> None:
        """Test case for create_job

        """
        pass

    async def test_get_all_jobs_status(self) -> None:
        """Test case for get_all_jobs_status

        """
        pass

    async def test_send_job_command(self) -> None:
        """Test case for send_job_command

        """
        pass


if __name__ == '__main__':
    unittest.main()
