# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.sync_api import SyncApi


class TestSyncApi(unittest.IsolatedAsyncioTestCase):
    """SyncApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SyncApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_sync_ack(self) -> None:
        """Test case for delete_sync_ack

        """
        pass

    async def test_get_delta_sync(self) -> None:
        """Test case for get_delta_sync

        """
        pass

    async def test_get_full_sync_for_user(self) -> None:
        """Test case for get_full_sync_for_user

        """
        pass

    async def test_get_sync_ack(self) -> None:
        """Test case for get_sync_ack

        """
        pass

    async def test_get_sync_stream(self) -> None:
        """Test case for get_sync_stream

        """
        pass

    async def test_send_sync_ack(self) -> None:
        """Test case for send_sync_ack

        """
        pass


if __name__ == '__main__':
    unittest.main()
