# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.server_api import ServerApi


class TestServerApi(unittest.IsolatedAsyncioTestCase):
    """ServerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ServerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_server_license(self) -> None:
        """Test case for delete_server_license

        """
        pass

    async def test_get_about_info(self) -> None:
        """Test case for get_about_info

        """
        pass

    async def test_get_server_config(self) -> None:
        """Test case for get_server_config

        """
        pass

    async def test_get_server_features(self) -> None:
        """Test case for get_server_features

        """
        pass

    async def test_get_server_license(self) -> None:
        """Test case for get_server_license

        """
        pass

    async def test_get_server_statistics(self) -> None:
        """Test case for get_server_statistics

        """
        pass

    async def test_get_server_version(self) -> None:
        """Test case for get_server_version

        """
        pass

    async def test_get_storage(self) -> None:
        """Test case for get_storage

        """
        pass

    async def test_get_supported_media_types(self) -> None:
        """Test case for get_supported_media_types

        """
        pass

    async def test_get_theme(self) -> None:
        """Test case for get_theme

        """
        pass

    async def test_get_version_history(self) -> None:
        """Test case for get_version_history

        """
        pass

    async def test_ping_server(self) -> None:
        """Test case for ping_server

        """
        pass

    async def test_set_server_license(self) -> None:
        """Test case for set_server_license

        """
        pass


if __name__ == '__main__':
    unittest.main()
