# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.stacks_api import StacksApi


class TestStacksApi(unittest.IsolatedAsyncioTestCase):
    """StacksApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = StacksApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_stack(self) -> None:
        """Test case for create_stack

        """
        pass

    async def test_delete_stack(self) -> None:
        """Test case for delete_stack

        """
        pass

    async def test_delete_stacks(self) -> None:
        """Test case for delete_stacks

        """
        pass

    async def test_get_stack(self) -> None:
        """Test case for get_stack

        """
        pass

    async def test_search_stacks(self) -> None:
        """Test case for search_stacks

        """
        pass

    async def test_update_stack(self) -> None:
        """Test case for update_stack

        """
        pass


if __name__ == '__main__':
    unittest.main()
