# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.deprecated_api import DeprecatedApi


class TestDeprecatedApi(unittest.IsolatedAsyncioTestCase):
    """DeprecatedApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DeprecatedApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_random(self) -> None:
        """Test case for get_random

        """
        pass


if __name__ == '__main__':
    unittest.main()
