# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.download_api import DownloadApi


class TestDownloadApi(unittest.IsolatedAsyncioTestCase):
    """DownloadApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DownloadApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_download_archive(self) -> None:
        """Test case for download_archive

        """
        pass

    async def test_get_download_info(self) -> None:
        """Test case for get_download_info

        """
        pass


if __name__ == '__main__':
    unittest.main()
