# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.o_auth_api import OAuthApi


class TestOAuthApi(unittest.IsolatedAsyncioTestCase):
    """OAuthApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = OAuthApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_finish_o_auth(self) -> None:
        """Test case for finish_o_auth

        """
        pass

    async def test_link_o_auth_account(self) -> None:
        """Test case for link_o_auth_account

        """
        pass

    async def test_redirect_o_auth_to_mobile(self) -> None:
        """Test case for redirect_o_auth_to_mobile

        """
        pass

    async def test_start_o_auth(self) -> None:
        """Test case for start_o_auth

        """
        pass

    async def test_unlink_o_auth_account(self) -> None:
        """Test case for unlink_o_auth_account

        """
        pass


if __name__ == '__main__':
    unittest.main()
