# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.partners_api import PartnersApi


class TestPartnersApi(unittest.IsolatedAsyncioTestCase):
    """PartnersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PartnersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_partner(self) -> None:
        """Test case for create_partner

        """
        pass

    async def test_get_partners(self) -> None:
        """Test case for get_partners

        """
        pass

    async def test_remove_partner(self) -> None:
        """Test case for remove_partner

        """
        pass

    async def test_update_partner(self) -> None:
        """Test case for update_partner

        """
        pass


if __name__ == '__main__':
    unittest.main()
