# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.people_api import PeopleApi


class TestPeopleApi(unittest.IsolatedAsyncioTestCase):
    """PeopleApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PeopleApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_person(self) -> None:
        """Test case for create_person

        """
        pass

    async def test_get_all_people(self) -> None:
        """Test case for get_all_people

        """
        pass

    async def test_get_person(self) -> None:
        """Test case for get_person

        """
        pass

    async def test_get_person_statistics(self) -> None:
        """Test case for get_person_statistics

        """
        pass

    async def test_get_person_thumbnail(self) -> None:
        """Test case for get_person_thumbnail

        """
        pass

    async def test_merge_person(self) -> None:
        """Test case for merge_person

        """
        pass

    async def test_reassign_faces(self) -> None:
        """Test case for reassign_faces

        """
        pass

    async def test_update_people(self) -> None:
        """Test case for update_people

        """
        pass

    async def test_update_person(self) -> None:
        """Test case for update_person

        """
        pass


if __name__ == '__main__':
    unittest.main()
