# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.map_api import MapApi


class TestMapApi(unittest.IsolatedAsyncioTestCase):
    """MapApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MapApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_map_markers(self) -> None:
        """Test case for get_map_markers

        """
        pass

    async def test_reverse_geocode(self) -> None:
        """Test case for reverse_geocode

        """
        pass


if __name__ == '__main__':
    unittest.main()
