# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.timeline_api import TimelineApi


class TestTimelineApi(unittest.IsolatedAsyncioTestCase):
    """TimelineApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TimelineApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_time_bucket(self) -> None:
        """Test case for get_time_bucket

        """
        pass

    async def test_get_time_buckets(self) -> None:
        """Test case for get_time_buckets

        """
        pass


if __name__ == '__main__':
    unittest.main()
