# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.memories_api import MemoriesApi


class TestMemoriesApi(unittest.IsolatedAsyncioTestCase):
    """MemoriesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MemoriesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_memory_assets(self) -> None:
        """Test case for add_memory_assets

        """
        pass

    async def test_create_memory(self) -> None:
        """Test case for create_memory

        """
        pass

    async def test_delete_memory(self) -> None:
        """Test case for delete_memory

        """
        pass

    async def test_get_memory(self) -> None:
        """Test case for get_memory

        """
        pass

    async def test_remove_memory_assets(self) -> None:
        """Test case for remove_memory_assets

        """
        pass

    async def test_search_memories(self) -> None:
        """Test case for search_memories

        """
        pass

    async def test_update_memory(self) -> None:
        """Test case for update_memory

        """
        pass


if __name__ == '__main__':
    unittest.main()
