# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.search_api import SearchApi


class TestSearchApi(unittest.IsolatedAsyncioTestCase):
    """SearchApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SearchApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_assets_by_city(self) -> None:
        """Test case for get_assets_by_city

        """
        pass

    async def test_get_explore_data(self) -> None:
        """Test case for get_explore_data

        """
        pass

    async def test_get_search_suggestions(self) -> None:
        """Test case for get_search_suggestions

        """
        pass

    async def test_search_assets(self) -> None:
        """Test case for search_assets

        """
        pass

    async def test_search_person(self) -> None:
        """Test case for search_person

        """
        pass

    async def test_search_places(self) -> None:
        """Test case for search_places

        """
        pass

    async def test_search_random(self) -> None:
        """Test case for search_random

        """
        pass

    async def test_search_smart(self) -> None:
        """Test case for search_smart

        """
        pass


if __name__ == '__main__':
    unittest.main()
