# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.trash_api import TrashApi


class TestTrashApi(unittest.IsolatedAsyncioTestCase):
    """TrashApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TrashApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_empty_trash(self) -> None:
        """Test case for empty_trash

        """
        pass

    async def test_restore_assets(self) -> None:
        """Test case for restore_assets

        """
        pass

    async def test_restore_trash(self) -> None:
        """Test case for restore_trash

        """
        pass


if __name__ == '__main__':
    unittest.main()
