# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.tags_api import TagsApi


class TestTagsApi(unittest.IsolatedAsyncioTestCase):
    """TagsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TagsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_bulk_tag_assets(self) -> None:
        """Test case for bulk_tag_assets

        """
        pass

    async def test_create_tag(self) -> None:
        """Test case for create_tag

        """
        pass

    async def test_delete_tag(self) -> None:
        """Test case for delete_tag

        """
        pass

    async def test_get_all_tags(self) -> None:
        """Test case for get_all_tags

        """
        pass

    async def test_get_tag_by_id(self) -> None:
        """Test case for get_tag_by_id

        """
        pass

    async def test_tag_assets(self) -> None:
        """Test case for tag_assets

        """
        pass

    async def test_untag_assets(self) -> None:
        """Test case for untag_assets

        """
        pass

    async def test_update_tag(self) -> None:
        """Test case for update_tag

        """
        pass

    async def test_upsert_tags(self) -> None:
        """Test case for upsert_tags

        """
        pass


if __name__ == '__main__':
    unittest.main()
