# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.134.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.users_api import UsersApi


class TestUsersApi(unittest.IsolatedAsyncioTestCase):
    """UsersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_profile_image(self) -> None:
        """Test case for create_profile_image

        """
        pass

    async def test_delete_profile_image(self) -> None:
        """Test case for delete_profile_image

        """
        pass

    async def test_delete_user_license(self) -> None:
        """Test case for delete_user_license

        """
        pass

    async def test_get_my_preferences(self) -> None:
        """Test case for get_my_preferences

        """
        pass

    async def test_get_my_user(self) -> None:
        """Test case for get_my_user

        """
        pass

    async def test_get_profile_image(self) -> None:
        """Test case for get_profile_image

        """
        pass

    async def test_get_user(self) -> None:
        """Test case for get_user

        """
        pass

    async def test_get_user_license(self) -> None:
        """Test case for get_user_license

        """
        pass

    async def test_search_users(self) -> None:
        """Test case for search_users

        """
        pass

    async def test_set_user_license(self) -> None:
        """Test case for set_user_license

        """
        pass

    async def test_update_my_preferences(self) -> None:
        """Test case for update_my_preferences

        """
        pass

    async def test_update_my_user(self) -> None:
        """Test case for update_my_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
