# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.models.job_name import JobName

class TestJobName(unittest.TestCase):
    """JobName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobName(self):
        """Test JobName"""
        # inst = JobName()

if __name__ == '__main__':
    unittest.main()
