# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.albums_api import AlbumsApi


class TestAlbumsApi(unittest.IsolatedAsyncioTestCase):
    """AlbumsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AlbumsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_assets_to_album(self) -> None:
        """Test case for add_assets_to_album

        """
        pass

    async def test_add_users_to_album(self) -> None:
        """Test case for add_users_to_album

        """
        pass

    async def test_create_album(self) -> None:
        """Test case for create_album

        """
        pass

    async def test_delete_album(self) -> None:
        """Test case for delete_album

        """
        pass

    async def test_get_album_info(self) -> None:
        """Test case for get_album_info

        """
        pass

    async def test_get_album_statistics(self) -> None:
        """Test case for get_album_statistics

        """
        pass

    async def test_get_all_albums(self) -> None:
        """Test case for get_all_albums

        """
        pass

    async def test_remove_asset_from_album(self) -> None:
        """Test case for remove_asset_from_album

        """
        pass

    async def test_remove_user_from_album(self) -> None:
        """Test case for remove_user_from_album

        """
        pass

    async def test_update_album_info(self) -> None:
        """Test case for update_album_info

        """
        pass

    async def test_update_album_user(self) -> None:
        """Test case for update_album_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
