# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.view_api import ViewApi


class TestViewApi(unittest.IsolatedAsyncioTestCase):
    """ViewApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ViewApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_assets_by_original_path(self) -> None:
        """Test case for get_assets_by_original_path

        """
        pass

    async def test_get_unique_original_paths(self) -> None:
        """Test case for get_unique_original_paths

        """
        pass


if __name__ == '__main__':
    unittest.main()
