# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.assets_api import AssetsApi


class TestAssetsApi(unittest.IsolatedAsyncioTestCase):
    """AssetsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AssetsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_check_bulk_upload(self) -> None:
        """Test case for check_bulk_upload

        checkBulkUpload
        """
        pass

    async def test_check_existing_assets(self) -> None:
        """Test case for check_existing_assets

        checkExistingAssets
        """
        pass

    async def test_delete_assets(self) -> None:
        """Test case for delete_assets

        """
        pass

    async def test_download_asset(self) -> None:
        """Test case for download_asset

        """
        pass

    async def test_get_all_user_assets_by_device_id(self) -> None:
        """Test case for get_all_user_assets_by_device_id

        getAllUserAssetsByDeviceId
        """
        pass

    async def test_get_asset_info(self) -> None:
        """Test case for get_asset_info

        """
        pass

    async def test_get_asset_statistics(self) -> None:
        """Test case for get_asset_statistics

        """
        pass

    async def test_get_random(self) -> None:
        """Test case for get_random

        """
        pass

    async def test_play_asset_video(self) -> None:
        """Test case for play_asset_video

        """
        pass

    async def test_replace_asset(self) -> None:
        """Test case for replace_asset

        replaceAsset
        """
        pass

    async def test_run_asset_jobs(self) -> None:
        """Test case for run_asset_jobs

        """
        pass

    async def test_update_asset(self) -> None:
        """Test case for update_asset

        """
        pass

    async def test_update_assets(self) -> None:
        """Test case for update_assets

        """
        pass

    async def test_upload_asset(self) -> None:
        """Test case for upload_asset

        """
        pass

    async def test_view_asset(self) -> None:
        """Test case for view_asset

        """
        pass


if __name__ == '__main__':
    unittest.main()
