# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.system_config_api import SystemConfigApi


class TestSystemConfigApi(unittest.IsolatedAsyncioTestCase):
    """SystemConfigApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemConfigApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_config(self) -> None:
        """Test case for get_config

        """
        pass

    async def test_get_config_defaults(self) -> None:
        """Test case for get_config_defaults

        """
        pass

    async def test_get_storage_template_options(self) -> None:
        """Test case for get_storage_template_options

        """
        pass

    async def test_update_config(self) -> None:
        """Test case for update_config

        """
        pass


if __name__ == '__main__':
    unittest.main()
