# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.api.system_metadata_api import SystemMetadataApi


class TestSystemMetadataApi(unittest.IsolatedAsyncioTestCase):
    """SystemMetadataApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemMetadataApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_admin_onboarding(self) -> None:
        """Test case for get_admin_onboarding

        """
        pass

    async def test_get_reverse_geocoding_state(self) -> None:
        """Test case for get_reverse_geocoding_state

        """
        pass

    async def test_update_admin_onboarding(self) -> None:
        """Test case for update_admin_onboarding

        """
        pass


if __name__ == '__main__':
    unittest.main()
