# coding: utf-8

"""
    Immich

    Immich API

    The version of the OpenAPI document: 1.133.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from immich_python_sdk_asyncio.models.source_type import SourceType

class TestSourceType(unittest.TestCase):
    """SourceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceType(self):
        """Test SourceType"""
        # inst = SourceType()

if __name__ == '__main__':
    unittest.main()
