name: Build and release immich-python-sdk

on:
  workflow_dispatch:
    inputs:
      immich-version:
        description: 'Immich version'
        type: string
        required: true
      immich-api-url:
        description: 'URL to immich openapi specification'
        type: string
        required: true


jobs:
  build-and-test:
    name: Generate & build SDK
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: v${{ inputs.immich-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.IMMICH_PYTHON_SDK_TOKEN }}

      - name: Create branch
        run: git checkout --orphan ${BRANCH_NAME}

      - name: Generate Python SDK
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          openapi-url: ${{ inputs.immich-api-url }}
          config-file: openapi_config.json
          command-args: "--additional-properties=\
            packageVersion=${{ inputs.immich-version }},\
            packageUrl=${{ github.repositoryUrl }}"

      - name: Move generated files
        run: find . -mindepth 1 -maxdepth 1 ! -name ".git" ! -name "python-client" -exec rm -rf {} + && mv python-client/{*,.*} . && rmdir python-client

      - name: Create commit & tag
        run: |
          git config user.email "action@github.com"
          git config user.name "Github Action"
          git add -A
          git commit -m "Generated immich-python-sdk for v${{ inputs.immich-version }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build SDK
        run: poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Push branch
        run: git push -u origin --force-with-lease ${BRANCH_NAME}
